os: linux
dist: xenial
language: ruby
rvm:
  - 2.6.3  # html-proofer requires Ruby version >= 2.6.0

install: gem install jekyll html-proofer jekyll-spaceship

addons:
  apt:
    packages:
      - libcurl4-openssl-dev  # Avoid ssl errors

script: jekyll build -s src -d ./site  && htmlproofer ./site

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: ./deploy.sh
