services:

  jekyll: &jekyll
    build:
      dockerfile: Dockerfile
    image: jekyll
    volumes:
      - ./src:/srv/jekyll
    stdin_open: true
    tty: true
    entrypoint: bundle exec jekyll
    command: --version

  jekyll-build:
    <<: *jekyll
    command: build
    container_name: jekyll-build

  jekyll-serve:
    <<: *jekyll
    ports:
      - 4000:4000
    command: serve --host 0.0.0.0 --trace
    container_name: jekyll-serve

  html-proofer:
    image: klakegg/html-proofer:3.17.0
    volumes:
      - ./src/_site:/src
    command: --allow-hash-href --check-html --empty-alt-ignore
    container_name: html-proofer

