title: Albert
email: manuelschneid3r@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Albert is a unified and efficient access to your machine. Technically it is a keyboard launcher
  written in C++/Qt. The plugin based architecture makes it extremely flexible and powerful. Plugins
  can be used to create frontends or functional extensions. Extensions can also be implemented
  using embedded Python modules or via a CGI approach in any language you want.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://albertlauncher.github.io
github_username:  manuelschneid3r
repository: https://github.com/albertlauncher
exclude: [vendor]
future: true

collections:
  pages:
    output: true

plugins:
  - jekyll-spaceship
