# frozen_string_literal: true
# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
source "https://rubygems.org"

gem "jekyll"
gem "webrick"
gem "just-the-docs"
gem 'jekyll-loading-lazy'


#gem "jekyll-default-layout"
#gem 'jekyll-spaceship'
#gem "jekyll-sass-converter", "~> 2.0"
